---
- name: Download and install patches
  hosts: #####
  gather_facts: yes
  tasks:

    # Task 1: Download updates without rebooting
    - name: Download available patches from WSUS
      win_updates:
        category_names:
          - "Security Updates"
          - "Critical Updates"
          - "Windows Software Malicious Removal Tool"
        state: downloaded
      register: download_result

    # Task 2: Install the downloaded updates
    - name: Install downloaded updates
      win_updates:
        category_names:
          - "Security Updates"
          - "Critical Updates"
        state: installed
      when: download_result.downloaded

    # Task 3: Check if a reboot is required
    - name: Check if a reboot is required
      win_service:
        name: wuauserv
        state: started
      register: update_service_status

    - name: Set reboot required flag
      set_fact:
        reboot_required: "{{ download_result.reboot_required or update_service_status.changed }}"

    # Task 4: Report that a reboot is required (if so)
    - name: Notify that a reboot is required (if applicable)
      debug:
        msg: "A reboot is required after patch installation. Please reboot the system."
      when: reboot_required

    # Task 5: Ensure no reboot occurs during the process
    - name: Ensure no reboot is performed
      win_reboot:
        reboot_timeout: 0
        test_command: "echo No Reboot"
      when: not reboot_required
      ignore_errors: yes

    # Task 6: Optionally log the results (you could store it somewhere or send an email, etc.)
    - name: Log the results of download and installation
      debug:
        msg: "Updates download complete and installed. Reboot required: {{ reboot_required }}"
