- name: Configure Ubuntu SSH Server
  hosts: ssh_servers
  become: true
  vars:
    ssh_user: "your_admin_user"  # Change this to the allowed SSH user

  tasks:
    - name: Ensure OpenSSH server is installed
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Start and enable SSH service
      systemd:
        name: ssh
        state: started
        enabled: yes

    - name: Ensure SSH is running before proceeding
      wait_for:
        port: 22
        timeout: 10

    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Enable UFW firewall
      command: ufw enable
      ignore_errors: yes  # Avoid failure if already enabled

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Reload UFW to apply rules
      command: ufw reload
      ignore_errors: yes

    - name: Configure SSH settings
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        backup: yes
      with_items:
        - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
        - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication yes" }
        - { regexp: "^AllowUsers", line: "AllowUsers {{ ssh_user }}" }

    - name: Restart SSH service to apply changes
      systemd:
        name: ssh
        state: restarted

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Start and enable Fail2Ban service
      systemd:
        name: fail2ban
        state: started
        enabled: yes
